apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: namespace
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: registry.gitlab.com/lucas.pleckspaen/gitlab-ks-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry.gitlab.com
